### ISSUE TITLE
I have these errors in plugin config...

### ISSUE THREAD

**Issue by dadoprom** [Pluxopolis/plxMyContact#18]
Warning: explode() expects parameter 2 to be string, array given in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMyContact/config.php on line 8

Warning: array_intersect(): Argument #1 is not an array in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMyContact/config.php on line 9

Warning: Invalid argument supplied for foreach() in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMyContact/config.php on line 40
Mail sending function available

Main
Warning: Invalid argument supplied for foreach() in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMyContact/config.php on line 81

I checked other plugins and there is aswell this error in plxMySearch

Warning: explode() expects parameter 2 to be string, array given in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMySearch/config.php on line 8

Warning: array_intersect(): Argument #1 is not an array in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMySearch/config.php on line 9

Warning: Invalid argument supplied for foreach() in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMySearch/config.php on line 39
Main
Warning: Invalid argument supplied for foreach() in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMySearch/config.php on line 77
Warning: Invalid argument supplied for foreach() in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMySearch/config.php on line 128

Warning: Invalid argument supplied for foreach() in /www/htdocs/w012ab4b/lovebirth.de/plugins/plxMyContact/config.php on line 116

Using latest rc versions of pluxml and the plugins... and also MultiLingue plugin
PHP verzia : 7.1.1-nmm1

**Comment by Pluxopolis** [comment]
You are using PluXml 5.6 with plxMyContact for PluXml 5.5
Please download the version from the master branch
https://github.com/Pluxopolis/plxMyContact/archive/master.zip
This one will be published when PluXml 5.6 will be released
Thanks

**Comment by dadoprom** [comment]
Ok, thank you very much. This one works, except when changing language on site the text on contact form is not changing... no switching translations...

I am using this hook in static.php template

<?php require 'plugins/plxMyContact/form.contact.php';  ?>

could this be the reason of not changing language?

**Comment by dadoprom** [comment]
This hook...
`<?php require 'plugins/plxMyContact/form.contact.php';  ?>`

**Comment by Pluxopolis** [comment]
If you add our own translation, edit file: /plugins/plxMyContact/config.php
change line : 
`	$aLangs = array_intersect($array, array('fr', 'en', 'es', 'oc', 'nl'));`
by
`	$aLangs = array_intersect($array, array('fr', 'en', 'es', 'oc', 'nl', 'sk'));`

Then go to config page of the plugin to change your setup.
No need to extra line in static page
